name: Build and Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build 
        run: python -m pip install build

      - name: Build wheels
        run: python -m build --wheel --sdist

      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-wheels-${{ matrix.os }}-${{ github.run_id }}
          path: dist

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://github.com/FledgeXu/PCDKit

    steps:
      - name: Download Ubuntu wheels
        uses: actions/download-artifact@v4
        with:
          name: built-wheels-ubuntu-latest-${{ github.run_id }}
          path: dist

      - name: Download Windows wheels
        uses: actions/download-artifact@v4
        with:
          name: built-wheels-windows-latest-${{ github.run_id }}
          path: dist

      - name: Download macOS wheels
        uses: actions/download-artifact@v4
        with:
          name: built-wheels-macos-latest-${{ github.run_id }}
          path: dist

      - name: Publish to PyPI via Trusted Publisher
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
